src/Entity/Meeting.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass="App\Repository\MeetingRepository")
 */
class Meeting
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min="10", max="255")
     */
    private $title;

    /**
     * @ORM\Column(type="text",  nullable=true)
     * @Assert\Length(min="60", max="400")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MeetingDate", mappedBy="meeting", orphanRemoval=true, cascade={"remove"})
     */
    private $dates;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="meetings")
     * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MeetingGuest", mappedBy="meeting", orphanRemoval=true, cascade={"remove"})
     */
    private $meetingGuests;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\MeetingDate", cascade={"persist", "remove"})
     */
    private $chosen_date;


    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->dates = new ArrayCollection();
        $this->guests = new ArrayCollection();
        $this->meetingGuests = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug () : string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function formatedCreatedAt () : string
    {
        return $this->getCreatedAt()->format('H:m:s d-m-Y');
    }

    /**
     * @return Collection|MeetingDate[]
     */
    public function getDates(): Collection
    {
        return $this->dates;
    }

    public function addDate(MeetingDate $date): self
    {
        if (!$this->dates->contains($date)) {
            $this->dates[] = $date;
            $date->setMeeting($this);
        }

        return $this;
    }

    public function removeDate(MeetingDate $date): self
    {
        if ($this->dates->contains($date)) {
            $this->dates->removeElement($date);
            // set the owning side to null (unless already changed)
            if ($date->getMeeting() === $this) {
                $date->setMeeting(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    /**
     * @param User|null $user
     * @return $this
     */
    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Guest[]
     */
    public function getGuests(): Collection
    {
        return $this->guests;
    }

    /**
     * @return Collection|MeetingGuest[]
     */
    public function getMeetingGuests(): Collection
    {
        return $this->meetingGuests;
    }

    public function addMeetingGuest(MeetingGuest $meetingGuest): self
    {
        if (!$this->meetingGuests->contains($meetingGuest)) {
            $this->meetingGuests[] = $meetingGuest;
            $meetingGuest->setMeeting($this);
        }

        return $this;
    }

    public function removeMeetingGuest(MeetingGuest $meetingGuest): self
    {
        if ($this->meetingGuests->contains($meetingGuest)) {
            $this->meetingGuests->removeElement($meetingGuest);
            // set the owning side to null (unless already changed)
            if ($meetingGuest->getMeeting() === $this) {
                $meetingGuest->setMeeting(null);
            }
        }

        return $this;
    }

    public function getChosenDate(): ?MeetingDate
    {
        return $this->chosen_date;
    }

    public function setChosenDate(?MeetingDate $chosen_date): self
    {
        $this->chosen_date = $chosen_date;

        return $this;
    }
}

src/Entity/MeetingDate.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MeetingDateRepository")
 */
class MeetingDate
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $day;

    /**
     * @ORM\Column(type="time")
     */
    private $start_at;

    /**
     * @ORM\Column(type="time")
     */
    private $end_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Meeting", inversedBy="dates")
     * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     */
    private $meeting;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Availability", mappedBy="meeting_date", orphanRemoval=true)
     */
    private $availabilities;

    /**
     * @ORM\Column(type="datetime")
     */
    private $create_at;


    public function __construct()
    {
        $this->user_id = new ArrayCollection();
        $this->availabilities = new ArrayCollection();
        $this->create_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStartAt(): ?\DateTimeInterface
    {
        return $this->start_at;
    }

    public function setStartAt(\DateTimeInterface $start_at): self
    {
        $this->start_at = $start_at;

        return $this;
    }

    public function getEndAt(): ?\DateTimeInterface
    {
        return $this->end_at;
    }

    public function setEndAt(\DateTimeInterface $end_at): self
    {
        $this->end_at = $end_at;

        return $this;
    }

    public function getMeeting(): ?Meeting
    {
        return $this->meeting;
    }

    public function setMeeting(?Meeting $meeting): self
    {
        $this->meeting = $meeting;

        return $this;
    }

    /**
     * @return Collection|Availability[]
     */
    public function getAvailabilities(): Collection
    {
        return $this->availabilities;
    }

    public function addAvailability(Availability $availability): self
    {
        if (!$this->availabilities->contains($availability)) {
            $this->availabilities[] = $availability;
            $availability->setMeetingDateId($this);
        }

        return $this;
    }

    public function removeAvailability(Availability $availability): self
    {
        if ($this->availabilities->contains($availability)) {
            $this->availabilities->removeElement($availability);
            // set the owning side to null (unless already changed)
            if ($availability->getMeetingDateId() === $this) {
                $availability->setMeetingDateId(null);
            }
        }

        return $this;
    }

    public function getDay(): ?\DateTimeInterface
    {
        return $this->day;
    }

    public function setDay(\DateTimeInterface $day): self
    {
        $this->day = $day;

        return $this;
    }

    /**
     * Return liste of people who are available for an meeting date
     * @return Collection
     */
    public function getDisposable(): Collection
    {
        $liste = new ArrayCollection();
        foreach($this->availabilities as $avaibilities) {
            if ($avaibilities->getChoice()) {
                $liste->add($avaibilities);
            }
        }
        return $liste;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeInterface $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Service\UploaderHelper;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @Vich\Uploadable
 * @UniqueEntity("username")
 * @UniqueEntity("email")
 */
class User implements UserInterface, \Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank(message="Please enter an email")
     * @Assert\Email()
     */
    private $email;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Meeting", mappedBy="user", orphanRemoval=true)
     */
    private $meetings;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageFilename;


    private $plainPassword;

    /**
     * @ORM\Column(type="boolean")
     */
    private $subscribeToNewsletter = false;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\GuestWithAccount", mappedBy="user", orphanRemoval=true)
     */
    private $guestWithAccounts;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Assert\Length(max="200")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=70, nullable=true)
     */
    private $facebook;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $twitter;

    public function __construct()
    {
        $this->meetings = new ArrayCollection();
        $this->guests = new ArrayCollection();
        $this->updated_at = new DateTime();
        $this->events = new ArrayCollection();
        $this->meetingGuests = new ArrayCollection();
        $this->guestWithAccounts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getPlainPassword() : ?string
    {
        return $this->plainPassword;
    }

    public function setPlainPassword(string $plainPassword): self
    {
        $this->plainPassword = $plainPassword;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @inheritDoc
     */
    public function getRoles()
    {
        return ['ROLE_ADMIN'];
    }

    /**
     * @inheritDoc
     */
    public function getSalt()
    {
        return null;
    }

    /**
     * @inheritDoc
     */
    public function eraseCredentials()
    {
    }

    /**
     * @inheritDoc
     */
    public function serialize()
    {
        return serialize([
            $this->id,
            $this->username,
            $this->password,
            $this->email
        ]);
    }

    /**
     * @inheritDoc
     */
    public function unserialize($serialized)
    {
        list(
            $this->id,
            $this->username,
            $this->password,
            $this->email
            ) = unserialize($serialized, ['allowed_classes' => false]);
    }

    /**
     * @return Collection|Meeting[]
     */
    public function getMeetings(): Collection
    {
        return $this->meetings;
    }

    public function addMeeting(Meeting $meeting): self
    {
        if (!$this->meetings->contains($meeting)) {
            $this->meetings[] = $meeting;
            $meeting->setUser($this);
        }

        return $this;
    }

    public function removeMeeting(Meeting $meeting): self
    {
        if ($this->meetings->contains($meeting)) {
            $this->meetings->removeElement($meeting);
            // set the owning side to null (unless already changed)
            if ($meeting->getUser() === $this) {
                $meeting->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return string|null
     */
    public function getImageFilename(): ?string
    {
        return $this->imageFilename;
    }

    /**
     * @param string|null $imageFilename
     * @return User
     */
    public function setImageFilename(?string $imageFilename): self
    {
        $this->imageFilename = $imageFilename;

        return $this;
    }

    public function getImagePath()
    {
        return  UploaderHelper::USER_IMAGE . '/' . $this->getImageFilename();
    }

    public function getSlug () : string
    {
        return (new Slugify())->slugify($this->username);
    }

    /**
     * @return Collection|GuestWithAccount[]
     */
    public function getGuestWithAccounts(): Collection
    {
        return $this->guestWithAccounts;
    }

    public function addGuestWithAccount(GuestWithAccount $guestWithAccount): self
    {
        if (!$this->guestWithAccounts->contains($guestWithAccount)) {
            $this->guestWithAccounts[] = $guestWithAccount;
            $guestWithAccount->setUser($this);
        }

        return $this;
    }

    public function removeGuestWithAccount(GuestWithAccount $guestWithAccount): self
    {
        if ($this->guestWithAccounts->contains($guestWithAccount)) {
            $this->guestWithAccounts->removeElement($guestWithAccount);
            // set the owning side to null (unless already changed)
            if ($guestWithAccount->getUser() === $this) {
                $guestWithAccount->setUser(null);
            }
        }

        return $this;
    }

    public function getSubscribeToNewsletter()
    {
        return $this->subscribeToNewsletter;
    }

    public function setSubscribeToNewsletter(bool $subscribeToNewsletter)
    {
        $this->subscribeToNewsletter = $subscribeToNewsletter;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getFacebook(): ?string
    {
        return $this->facebook;
    }

    public function setFacebook(?string $facebook): self
    {
        $this->facebook = $facebook;

        return $this;
    }

    public function getTwitter(): ?string
    {
        return $this->twitter;
    }

    public function setTwitter(?string $twitter): self
    {
        $this->twitter = $twitter;

        return $this;
    }
}

src/Controller/Meeting/MeetingController.php
<?php


namespace App\Controller\Meeting;


use App\Repository\AvailabilityRepository;
use App\Repository\MeetingGuestRepository;
use App\Repository\MeetingRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

/**
 * Class MeetingController
 * @package App\Controller\Meeting
 */
class MeetingController extends AbstractController
{
    private $manager;

    private $meetingRepository;

    private $meetingGuestRepository;

    public function __construct(EntityManagerInterface $manager, MeetingRepository $meetingRepository, MeetingGuestRepository $meetingGuestRepository)
    {
        $this->manager = $manager;
        $this->meetingRepository = $meetingRepository;
        $this->meetingGuestRepository = $meetingGuestRepository;
    }

    /**
     *
     * @Route("/meetings", name="meeting.view")
     * @param Security $security
     * @return Response
     */
    public function index (Security $security): Response
    {
        $user = $security->getUser();
        $event = $this->meetingGuestRepository->findMeetingWithUserId($user->getId());
        $my_meeting = $this->meetingRepository->findAllById($user->getId());

        return $this->render("event/show.html.twig", [
            'current_menu' => 'events',
            'events' => $event,
            'my_meeting' => $my_meeting,
        ]);

    }
}

templates/meeting/__availability_card.html.twig
{% if guest.guestWithAccount %}
    {% if availability is defined %}
        {% if availability.choice == true %}
            <a href="#" class="btn btn-primary js-meeting-date-choice" data-url="{{ path('meeting_date.choice.refuse', {id_meeting_date: date.id, id: guest.id}) }}">Not disposable</a>
        {% else %}
            <a href="#" class="btn btn-primary js-meeting-date-choice" data-url="{{ path('meeting_date.choice.accept', {id_meeting_date: date.id, id: guest.id}) }}">Disposable</a>
        {% endif %}
        <a href="#" class="btn btn-danger js-meeting-date-choice-cancel" data-url="{{ path('availability.cancel', {id: availability.id}) }}">
            <span class="fa fa-times"> </span>
        </a>
    {% else %}
        <a href="#" class="btn btn-primary js-meeting-date-choice" data-url="{{ path('meeting_date.choice.accept', {id_meeting_date: date.id, id: guest.id}) }}">Disposable</a>
        <a href="#" class="btn btn-primary js-meeting-date-choice" data-url="{{ path('meeting_date.choice.refuse', {id_meeting_date: date.id, id: guest.id}) }}">Not disposable</a>
    {% endif %}
{% else %}
    {% if availability is defined %}
        {% if availability.choice == true %}
            <a href="#" class="btn btn-primary js-meeting-date-choice" data-url="{{ path('meeting_date_choice.refuse_without_account', {id_meeting_date: date.id, id: guest.id, token: guest.guestWithoutAccount.token}) }}">Not disposable</a>
        {% else %}
            <a href="#" class="btn btn-primary js-meeting-date-choice" data-url="{{ path('meeting_date_choice.accept_without_account', {id_meeting_date: date.id, id: guest.id, token: guest.guestWithoutAccount.token}) }}">Disposable</a>
        {% endif %}
        <a href="#" class="btn btn-danger js-meeting-date-choice-cancel" data-url="{{ path('availability.cancel_without_account', {id: availability.id, token: guest.guestWithoutAccount.token}) }}">
            <span class="fa fa-times"> </span>
        </a>
    {% else %}
        <a href="#" class="btn btn-primary js-meeting-date-choice" data-url="{{ path('meeting_date_choice.accept_without_account', {id_meeting_date: date.id, id: guest.id, token: guest.guestWithoutAccount.token}) }}">Disposable</a>
        <a href="#" class="btn btn-primary js-meeting-date-choice" data-url="{{ path('meeting_date_choice.refuse_without_account', {id_meeting_date: date.id, id: guest.id, token: guest.guestWithoutAccount.token}) }}">Not disposable</a>
    {% endif %}
{% endif %}

templates/meeting/__meeting_date_card.html.twig
<div class="card text-center meeting-date-card-availability">
    <div class="card-header bg-info">
        <h2 class="title">The {{ date.day|date("j F Y") }}</h2>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-4 offset-2 border-right border-danger">
                <h5 class="title__min">Start at</h5>
                <p>{{ date.startAt|date('H:i') }}</p>
            </div>
            <div class="col-4">
                <h5 class="title__min">End at</h5>
                <p>{{ date.endAt|date('H:i') }}</p>
            </div>
        </div>
        <div class="js-availability-wrapper">
            {% if guest.guestWithAccount %}
                {% if availability is defined %}
                    {% set break = false %}
                    {% for choice in availability %}
                        {% if choice.meetingDate.id == date.id %}
                            {% set break = true %}
                            {% if choice.choice == true %}
                                <a href="#" class="btn btn-primary js-meeting-date-choice" data-url="{{ path('meeting_date.choice.refuse', {id_meeting_date: date.id, id: guest.id}) }}">Not disposable</a>
                            {% else %}
                                <a href="#" class="btn btn-primary js-meeting-date-choice" data-url="{{ path('meeting_date.choice.accept', {id_meeting_date: date.id, id: guest.id}) }}">Disposable</a>
                            {% endif %}
                            <a href="#" class="btn btn-danger js-meeting-date-choice-cancel" data-url="{{ path('availability.cancel', {id: choice.id}) }}">
                                <span class="fa fa-times"> </span>
                            </a>
                        {% endif %}
                    {% endfor %}
                    {% if not break %}
                        <a href="#" class="btn btn-primary js-meeting-date-choice" data-url="{{ path('meeting_date.choice.accept', {id_meeting_date: date.id, id: guest.id}) }}">Disposable</a>
                        <a href="#" class="btn btn-primary js-meeting-date-choice" data-url="{{ path('meeting_date.choice.refuse', {id_meeting_date: date.id, id: guest.id}) }}">Not disposable</a>
                    {% endif %}
                {% else %}
                    <a href="#" class="btn btn-primary js-meeting-date-choice" data-url="{{ path('meeting_date.choice.accept', {id_meeting_date: date.id, id: guest.id}) }}">Disposable</a>
                    <a href="#" class="btn btn-primary js-meeting-date-choice" data-url="{{ path('meeting_date.choice.refuse', {id_meeting_date: date.id, id: guest.id}) }}">Not disposable</a>
                {% endif %}
            {% else %}
                {% if availability is defined %}
                    {% set break = false %}
                    {% for choice in availability %}
                        {% if choice.meetingDate.id == date.id %}
                            {% set break = true %}
                            {% if choice.choice == true %}
                                <a href="#" class="btn btn-primary js-meeting-date-choice" data-url="{{ path('meeting_date_choice.refuse_without_account', {id_meeting_date: date.id, id: guest.id, token: guest.guestWithoutAccount.token}) }}">Not disposable</a>
                            {% else %}
                                <a href="#" class="btn btn-primary js-meeting-date-choice" data-url="{{ path('meeting_date_choice.accept_without_account', {id_meeting_date: date.id, id: guest.id, token: guest.guestWithoutAccount.token}) }}">Disposable</a>
                            {% endif %}
                            <a href="#" class="btn btn-danger js-meeting-date-choice-cancel" data-url="{{ path('availability.cancel_without_account', {id: choice.id, token: guest.guestWithoutAccount.token}) }}">
                                <span class="fa fa-times"> </span>
                            </a>
                        {% endif %}
                    {% endfor %}
                    {% if not break %}
                        <a href="#" class="btn btn-primary js-meeting-date-choice" data-url="{{ path('meeting_date_choice.accept_without_account', {id_meeting_date: date.id, id: guest.id, token: guest.guestWithoutAccount.token}) }}">Disposable</a>
                        <a href="#" class="btn btn-primary js-meeting-date-choice" data-url="{{ path('meeting_date_choice.refuse_without_account', {id_meeting_date: date.id, id: guest.id, token: guest.guestWithoutAccount.token}) }}">Not disposable</a>
                    {% endif %}
                {% else %}
                    <a href="#" class="btn btn-primary js-meeting-date-choice" data-url="{{ path('meeting_date_choice.accept_without_account', {id_meeting_date: date.id, id: guest.id, token: guest.guestWithoutAccount.token}) }}">Disposable</a>
                    <a href="#" class="btn btn-primary js-meeting-date-choice" data-url="{{ path('meeting_date_choice.refuse_without_account', {id_meeting_date: date.id, id: guest.id, token: guest.guestWithoutAccount.token}) }}">Not disposable</a>
                {% endif %}
            {% endif %}
        </div>
    </div>
    <div class="card-footer text-black bg-transparent">
        <p>Create the {{ date.createAt|date('d-m-Y \\a\\t H:i') }}</p>
    </div>
</div>

templates/meeting/__profile_card.html.twig
<div class="col-md-6 px-0 offset-md-3 offset-xl-0">
    <div class="card pp-card">
        <img src="{{ uploaded_asset(meeting.user.imagePath) | imagine_filter('square150') }}" alt="" width="100%"/>
        <h5 class="username">{{ meeting.user.username }}</h5>
        <p class="pl-2">{{ meeting.user.description }}</p>
        <ul>
            <li>
                <a href="https://twitter.com/{{ meeting.user.twitter }}" class="text-black"><i class="fa fa-twitter fa-2x"> </i></a>
            </li>
            <li>
                <a href="#" class="text-black"><i class="fa fa-facebook fa-2x"> </i></a>
            </li>
        </ul>
    </div>
</div>

templates/meeting/index.html.twig
{% extends 'base.html.twig' %}
{% block title 'My meeting\'s' %}
{% block body %}
    <div class="container">
        <h1>Meeting's</h1>
        <div class="row flex">
            {% for meeting in meetings %}
                <div class="col-3">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">
                                <a href="{{ path('meeting.show', {id: meeting.id, slug: meeting.slug}) }}">{{ meeting.title }}</a>
                            </h5>
                            <p class="card-text">{{ meeting.description }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/meeting/show.html.twig
{% extends 'base.html.twig' %}
{% block title meeting.title%}
{% block body %}
    <div class="container" style="margin-top: 4cm">
        {% if meeting.chosenDate %}
            <h1 class="meeting-h1">Meeting start the <strong>{{ meeting.chosenDate.day|date('F jS') }}</strong> at <strong>{{ meeting.chosenDate.startAt|date('H:i') }}</strong> and finish at <strong>{{ meeting.chosenDate.endAt|date('H:i') }}</strong></h1>
        {% endif %}
        <div class="row">
            <div class="offset-1 col-10 offset-sm-1 col-sm-10 col-md-10 offset-md-1 col-lg-10 offset-lg-1 col-xl-4 offset-xl-0">
                <div class="pl-md-5">
                    {{ include('meeting/__profile_card.html.twig') }}
                </div>
            </div>
            <div class="offset-1 col-10 offset-sm-1 col-sm-10 col-md-10 offset-md-1 col-lg-10 offset-lg-1 col-xl-8 offset-xl-0">
                <div class="jumbotron p-3 p-md-5 meeting-date-info">
                    <h2 class="title">{{ meeting.title }}</h2>
                    <p class="lead my-3 text-black"><span class="pl-1 pr-3"><i class="fa-info fa"> </i></span>{{ meeting.description }}</p>
                    <p class="lead mb-0 text-black"><span class="pr-2"><i class="fa-calendar fa"> </i></span>Launch the {{ meeting.createdAt|date('F j, Y \\a\\t g:i a') }}</p>
                </div>
            </div>
        </div>
        {% if meeting.chosenDate %}
            <p class="text-black">The meeting will start soon !</p>
        {% else %}
            <div class="owl-carousel mt-3" id="js-meeting-date-choice-wrapper">
                {% for date in meetingDate %}
                    <div class="item">
                        {{ include('meeting/__meeting_date_card.html.twig') }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>

{% endblock %}

{% block javascripts %}
    <script type="text/javascript">
        $('.owl-carousel').owlCarousel({
            margin:20,
            autoWidth: true,
            responsiveClass:true,
            responsive : {
                0 : {
                    items : 1,
                },
                480 : {
                    items : 1,
                    center: true
                },
                768 : {
                    items : 1,
                }
            },
            loop:false,
            autoHeight: true,
        });
    </script>
    <script src="{{ asset('js/Availability.js') }}"></script>
    <script type="text/javascript">
        $meetingDateWrapper = $('#js-meeting-date-choice-wrapper');
        new Availability($meetingDateWrapper);
    </script>
{% endblock %}