src/Entity/Availability.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AvailabilityRepository")
 */
class Availability
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="boolean")
     */
    private $choice;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\MeetingGuest", inversedBy="availabilities")
     * @ORM\JoinColumn(nullable=false)
     */
    private $meeting_guest;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\MeetingDate", inversedBy="availabilities")
     * @ORM\JoinColumn(nullable=false)
     */
    private $meeting_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $chosen_at;

    public function __construct()
    {
        $this->meeting = new ArrayCollection();
        $this->chosen_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getChoice(): ?bool
    {
        return $this->choice;
    }

    public function setChoice(bool $choice): self
    {
        $this->choice = $choice;

        return $this;
    }
    
    public function removeMeeting(MeetingDate $meetingId): self
    {
        if ($this->meeting_id->contains($meetingId)) {
            $this->meeting_id->removeElement($meetingId);
        }

        return $this;
    }

    public function getMeetingGuest(): ?MeetingGuest
    {
        return $this->meeting_guest;
    }

    public function setMeetingGuest(?MeetingGuest $meeting_guest): self
    {
        $this->meeting_guest = $meeting_guest;

        return $this;
    }

    public function getMeetingDate(): ?MeetingDate
    {
        return $this->meeting_date;
    }

    public function setMeetingDate(?MeetingDate $meeting_date): self
    {
        $this->meeting_date = $meeting_date;

        return $this;
    }

    public function getChosenAt(): ?\DateTimeInterface
    {
        return $this->chosen_at;
    }

    public function setChosenAt(\DateTimeInterface $chosen_at): self
    {
        $this->chosen_at = $chosen_at;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Plannificateur reunion{% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-sweetalert/1.0.1/sweetalert.min.css">
        {{ encore_entry_link_tags('app') }}
        <link rel="stylesheet" href="{{ asset('fonts/icomoon/style.css') }}">
        <link rel="stylesheet" href="{{ asset('css/magnific-popup.css') }}">
        <link rel="stylesheet" href="{{ asset('css/jquery-ui.css') }}">
        <link rel="stylesheet" href="{{ asset('css/owl.carousel.min.css') }}">
        <link rel="stylesheet" href="{{ asset('css/owl.theme.default.min.css') }}">
        <link rel="stylesheet" href="{{ asset('css/animate.css') }}">
        <link rel="stylesheet" href="{{ asset('fonts/flaticon/font/flaticon.css') }}">
        <link rel="stylesheet" href="{{ asset('css/style.css') }}">
        <link rel="stylesheet" href="{{ asset('css/aos.css') }}">
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        <div class="site-wrap">
            <div class="site-mobile-menu">
                <div class="site-mobile-menu-header">
                    <div class="site-mobile-menu-close mt-3">
                        <span class="icon-close2 js-menu-toggle"></span>
                    </div>
                </div>
                <div class="site-mobile-menu-body"></div>
            </div><!-- .site-mobile-menu-->
            
            <div class="site-navbar-wrap js-site-navbar bg-white">
                <div class="container">
                    <div class="site-navbar bg-light">
                        <div class="py-1">
                            <div class="row align-items-center">
                                <div class="col-2">
                                    <h2 class="mb-0 site-logo">
                                        <a href="{{ path('home') }}">Mee/ting</a>
                                    </h2>
                                </div>
                                <div class="col-10">
                                    <nav class="site-navigation text-right" role="navigation">
                                        <div class="container">
                                            <div class="d-inline-block d-lg-none ml-md-0 mr-auto py-3">
                                                <a href="#" class="site-menu-toggle js-menu-toggle text-black">
                                                    <span class="icon-menu h3"></span>
                                                </a>
                                            </div>
                                            <ul class="site-menu js-clone-nav d-none d-lg-block">
                                                <li class="{% if current_menu is defined and current_menu == 'home' %}active underline{% else %}item-menu{% endif %}">
                                                    <a href="{{ path('home') }}">Home</a>
                                                </li>
                                                {% if app.user %}
                                                    <li class="
                                                        {% if current_menu is defined and current_menu == 'events' %}
                                                            active underline
                                                        {% else %}item-menu
                                                        {% endif %}
                                                        {% if app.user.guestWithAccounts.count > 0 %}
                                                            has-children
                                                        {% endif %}"
                                                    >
                                                        <a href="{{ path('meeting.view') }}">Events</a>

                                                        {% if app.user.guestWithAccounts.count > 0 %}
                                                            <span class="notification" style="padding: 0">{{ app.user.guestWithAccounts.count }}</span>
                                                            <ul class="dropdown arrow-top">
                                                                {% for guest in app.user.guestWithAccounts %}
                                                                    <li><a href="{{ path('meeting.show', {id: guest.meetingGuest.meeting.id, slug: guest.meetingGuest.meeting.slug}) }}">{{guest.meetingGuest.meeting.title}}</a></li>
                                                                {% endfor %}
                                                            </ul>
                                                        {% endif %}
                                                    </li>
                                                    <li class="{% if current_menu is defined and current_menu == 'admin' %}active underline{% else %}item-menu{% endif %}">
                                                        <a href="{{ path('admin.meeting.index') }}">My meetings</a>
                                                    </li>
                                                    <li class="{% if current_menu is defined and current_menu == 'myaccount' %}active underline{% else %}item-menu{% endif %}">
                                                        <a href="{{ path('admin.user.show', {slug: app.user.slug}) }}">{{ app.user.username }}</a>
                                                    </li>
                                                {% endif %}
                                                <li class="{% if current_menu is defined and current_menu == 'login' %}active underline{% else %}item-menu{% endif %}">
                                                    {% if app.user %}
                                                        <a href="{{ path('logout') }}">Log out</a>
                                                    {% else %}
                                                        <a href="{{ path('login') }}">Log in</a>
                                                    {% endif %}
                                                </li>
                                            </ul>
                                        </div>
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <!-- End navbar -->
            <div class="mt-5">
                {% block body %}{% endblock %}
            </div>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

        <script src="{{ asset('js/jquery-migrate-3.0.1.min.js') }}"></script>
        <script src="{{ asset('js/jquery-ui.js') }}"></script>
        <script src="{{ asset('js/owl.carousel.min.js') }}"></script>
        <script src="{{ asset('js/jquery.stellar.min.js') }}"></script>
        <script src="{{ asset('js/jquery.countdown.min.js') }}"></script>
        <script src="{{ asset('js/jquery.magnific-popup.min.js') }}"></script>
        <script src="{{ asset('js/bootstrap-datepicker.min.js') }}"></script>
        <script src="{{ asset('js/aos.js') }}"></script>
        <script src="{{ asset('js/main.js') }}"></script>
        {{ encore_entry_script_tags('app') }}
        <script>
            $('.custom-file-input').on('change', function (e) {
                let inputFile = e.currentTarget;
                $(inputFile).parent()
                    .find('.custom-file-label')
                    .html(inputFile.files[0].name)
            });
        </script>
        {% block javascripts %} {% endblock %}
    </body>
</html>